import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.support.ui.ExpectedCondition;
import org.openqa.selenium.support.ui.WebDriverWait;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'mrsqu' at '21.02.17 23:18' with Gradle 2.14.1
 *
 * @author mrsqu, @date 21.02.17 23:18
 */
public class ExampleTest {
    public static void main(String[] args) {
    	System.setProperty("webdriver.gecko.driver","C:\\Users\\mrsqu\\Documents\\GitHub\\FirefoxWebDriver\\geckodriver.exe");
    	WebDriver driver = new FirefoxDriver();
    	driver.get("https://google.com");
    	WebElement element = driver.findElement(By.name("q"));
    	element.sendKeys("wikipedia");
    	element.submit();
    	(new WebDriverWait(driver, 10)).until(new ExpectedCondition<Boolean>() {
            public Boolean apply(WebDriver d) {
                return d.getTitle().toLowerCase().startsWith("wikipedia");
            }
        });
    	System.out.println("Title " + driver.getTitle());
    	driver.quit();
    }
}
