/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mrsqu' at '22.02.17 0:02' with Gradle 2.14.1
 *
 * @author mrsqu, @date 22.02.17 0:02
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
